modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[38,)" #mandatory (28 is current forge version)

license="GNU General Public License v3.0"

[[mods]] #mandatory
modId="map_atlases" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Map Atlases" #mandatory
logoFile="icon.png" #optional
credits="pepperoni jabroni for the original mod, caltinor for making the previous forge port" #optional
authors="pepperoni jabroni, lilypuree" #optional
description='''
A Vanilla Style mapping mod
'''

[[dependencies.map_atlases]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.map_atlases]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
